[package]
name          = "ecdsa"
version       = "0.7.0-pre" # Also update html_root_url in lib.rs when bumping this
description   = """
Signature and elliptic curve types providing interoperable support for the
Elliptic Curve Digital Signature Algorithm (ECDSA)
"""
authors       = ["RustCrypto Developers"]
license       = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/ecdsa"
repository    = "https://github.com/RustCrypto/signatures"
edition       = "2018"
readme        = "README.md"
categories    = ["cryptography", "no-std"]
keywords      = ["crypto", "ecc", "nist", "secp256k1", "signature"]

[dependencies.elliptic-curve]
version = "= 0.5.0-pre"
default-features = false
features = ["weierstrass"]

[dependencies.signature]
version = ">= 1.2.2, < 1.3.0"
default-features = false

[features]
default = ["digest", "std"]
dev = []
digest = ["signature/digest-preview"]
hazmat = []
rand = ["elliptic-curve/rand_core", "signature/rand-preview"]
signer = ["digest", "hazmat", "rand", "zeroize"] # TODO(tarcieri): deterministic signing
std = ["elliptic-curve/std", "signature/std"]
zeroize = ["elliptic-curve/zeroize"]

[package.metadata.docs.rs]
features = ["digest", "std"]
rustdoc-args = ["--cfg", "docsrs"]
