[package]
name = "rfc6979"
version = "0.1.0"
authors    = ["RustCrypto Developers"]
license    = "Apache-2.0 OR MIT"
repository = "https://github.com/RustCrypto/signatures"
edition    = "2018"
description   = """
Support library for the ecdsa crate which provides deterministic generation
of k values according to RFC6979
"""
readme     = "README.md"
categories = ["cryptography", "no-std"]
keywords   = ["crypto", "deterministic", "dsa", "ecdsa", "signature"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = { version = "0.10", default-features = false }

[dev-dependencies]
hex-literal = "0.3"
sha2 = { version = "0.9", default-features = false }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
