[workspace]
members = ["ecdsa", "ed25519"]

[patch.crates-io]
crypto-bigint = { git = "https://github.com/rustcrypto/utils.git" }
der = { git = "https://github.com/rustcrypto/utils.git" }
elliptic-curve = { git = "https://github.com/rustcrypto/traits.git" }
pkcs8 = { git = "https://github.com/rustcrypto/utils.git" }
