[package]
name = "dsa"
version = "0.1.0"
authors = ["QiangHeisenberg <lziqiang1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.6", features = ["i128", "u64_digit", "prime", "zeroize"], default-features = false, package = "num-bigint-dig" }
num-traits = { version= "0.2.9", default-features = false, features = ["libm"] }
num-integer = { version = "0.1.39", default-features = false }
num-iter = { version = "0.1.37", default-features = false }
# lazy_static = { version = "1.3.0", features = ["spin_no_std"] }
rand = { version = "0.8.0", default-features = false }
# byteorder = { version = "1.3.1", default-features = false }
# subtle = { version = "=2.1.1", default-features = false }
# simple_asn1 = { version = "0.5", optional = true }
# pem = { version = "0.8", optional = true }
# digest = { version = "0.9.0", default-features = false }
num-bigint-dig = "0.4"

# [dependencies.zeroize]
# version = "1.1.0"
# features = ["alloc", "zeroize_derive"]

# [dependencies.serde_crate]
# package = "serde"
# optional = true
# version = "1.0.89"
# default-features = false
# features = ["derive"]

# [dev-dependencies]
# base64 = "0.12.0"
# hex = "0.4.0"
# serde_test = "1.0.89"
# rand_xorshift = "0.2.0"
# pem = "0.8"
# sha-1 = { default-features = false, version = "0.9.0" }
# sha2 = { default-features = false, version = "0.9.0" }
# sha3 = { default-features = false, version = "0.9.0" }

# [features]
# default = ["std", "pem"]
# nightly = ["subtle/nightly", "num-bigint/nightly"]
# serde = ["num-bigint/serde", "serde_crate"]
# serde1 = ["serde"] # deprecated
# expose-internals = []
# std = ["alloc", "simple_asn1", "digest/std", "rand/std"]
# alloc = ["digest/alloc"]
